import streamlit as st
import pandas as pd
import time

# =========================================
# 1. إعداد الصفحة الأساسي والهوية البصرية
# =========================================
st.set_page_config(
    page_title="LABEEB AI - لبيب",
    page_icon="🧠",
    layout="wide"
)

# تعيين النمط الجمالي والـ CSS بأمان كامل لتجنب تداخل علامات الاقتباس
st.markdown('<style>'
' @import url("https://fonts.googleapis.com/css2?family=Cairo:wght@300;400;600;700;800&display=swap");'
' html, body, [class*="css"] {'
'     font-family: "Cairo", sans-serif;'
'     direction: rtl;'
'     text-align: right;'
' }'
' .stApp {'
'     background: linear-gradient(135deg, #F8FAFC 0%, #F5F3FF 50%, #EFF6FF 100%) !important;'
' }'
' #MainMenu, footer, header {visibility: hidden;}'
' [data-testid="stMain"] .block-container {'
'     max-width: 1140px;'
'     padding-top: 2rem;'
'     padding-bottom: 4rem;'
'     margin: 0 auto;'
' }'
' /* HERO SECTION */'
' .hero-container {'
'     position: relative;'
'     background: linear-gradient(135deg, rgba(255, 255, 255, 0.85), rgba(243, 232, 255, 0.7));'
'     backdrop-filter: blur(20px);'
'     border: 1px solid rgba(255, 255, 255, 0.6);'
'     border-radius: 28px;'
'     padding: 45px 25px;'
'     text-align: center;'
'     box-shadow: 0 20px 40px rgba(109, 40, 217, 0.03);'
'     margin-bottom: 30px;'
' }'
' .hero-logo-glow {'
'     width: 85px;'
'     height: 85px;'
'     background: linear-gradient(135deg, #4F46E5, #6D28D9);'
'     border-radius: 50%;'
'     display: flex;'
'     align-items: center;'
'     justify-content: center;'
'     margin: 0 auto 18px auto;'
'     box-shadow: 0 0 25px rgba(109, 40, 217, 0.3);'
'     font-size: 36px;'
'     color: white;'
' }'
' .hero-title {'
'     font-size: 44px;'
'     font-weight: 800;'
'     background: linear-gradient(90deg, #6D28D9, #4F46E5);'
'     -webkit-background-clip: text;'
'     -webkit-text-fill-color: transparent;'
'     margin-bottom: 8px;'
' }'
' .hero-subtitle {'
'     font-size: 22px;'
'     font-weight: 700;'
'     color: #1E293B;'
'     margin-bottom: 12px;'
' }'
' .hero-desc {'
'     font-size: 16px;'
'     color: #64748B;'
'     max-width: 650px;'
'     margin: 0 auto 20px auto;'
'     line-height: 1.7;'
' }'
' .badge-student {'
'     display: inline-block;'
'     background: rgba(255, 255, 255, 0.9);'
'     border: 1px solid #E9D5FF;'
'     padding: 6px 18px;'
'     border-radius: 999px;'
'     font-size: 13px;'
'     font-weight: 600;'
'     color: #6D28D9;'
' }'
' /* GLASS CARDS */'
' .glass-card {'
'     background: rgba(255, 255, 255, 0.85);'
'     backdrop-filter: blur(20px);'
'     border: 1px solid rgba(255, 255, 255, 0.5);'
'     border-radius: 22px;'
'     padding: 30px;'
'     box-shadow: 0 10px 30px rgba(0, 0, 0, 0.01);'
'     margin-bottom: 25px;'
' }'
' .card-title {'
'     font-size: 20px;'
'     font-weight: 700;'
'     color: #1E293B;'
'     margin-bottom: 16px;'
'     display: flex;'
'     align-items: center;'
'     gap: 8px;'
' }'
' .stTextArea textarea {'
'     border-radius: 14px !important;'
'     border: 1px solid #E2E8F0 !important;'
'     padding: 16px !important;'
'     font-size: 16px !important;'
'     background: rgba(255, 255, 255, 0.7) !important;'
'     font-family: "Cairo", sans-serif !important;'
' }'
' .stButton > button {'
'     background: linear-gradient(90deg, #4F46E5, #6D28D9) !important;'
'     color: white !important;'
'     border: none !important;'
'     border-radius: 12px !important;'
'     padding: 12px 28px !important;'
'     font-size: 16px !important;'
'     font-weight: 700 !important;'
'     width: 100% !important;'
'     font-family: "Cairo", sans-serif !important;'
'     box-shadow: 0 6px 16px rgba(109, 40, 217, 0.15) !important;'
'     transition: all 0.2s ease;'
' }'
' .stButton > button:hover {'
'     transform: translateY(-1px);'
'     box-shadow: 0 10px 20px rgba(109, 40, 217, 0.25) !important;'
' }'
' /* RESULT COMPONENT */'
' .result-status-empty {'
'     text-align: center;'
'     color: #94A3B8;'
'     font-size: 15px;'
'     padding: 25px 0;'
' }'
' .result-badge-container {'
'     display: flex;'
'     gap: 14px;'
'     margin-bottom: 20px;'
' }'
' .result-stat-box {'
'     flex: 1;'
'     background: white;'
'     border: 1px solid #F3E8FF;'
'     padding: 14px;'
'     border-radius: 14px;'
'     text-align: center;'
' }'
' .result-stat-label {'
'     font-size
